
% Basic PPI analysis parameters
% There is a bug when specifying 'outdir'
P = struct( ...
    'subject', 'testsubj', ...
    'directory', [pwd '/../OUTPUTS/spm_nvs'], ...
    'VOI', [pwd '/../rois/BNST_L.nii.gz'], ...
    'Region', 'BNST_L', ...
    'analysis', 'psy', ...
    'method', 'cond', ...
    'extract', 'eig', ...
    'Contrast', 0, ...
    'Estimate', 1, ...
    'equalroi', 1, ...
    'FLmask', 0, ...
    'CompContrasts', 1, ...
    'Weighted', 0, ...
    'SPMver', '12', ...
    'preservevarcorr', 1 ...
    );


% Tasks to include in PPI analyses
P.Tasks = { ...
    '1' ...
    'Cue_Neutral' ...
    'Cue_Fear' ...
    'Cue_Unknown' ...
    'Image_Neutral' ...
    'Image_Fear' ...
    'Image_Unknown_Neutral' ...
    'Image_Unknown_Fear' ...
    };
P.Weights = [];


% Contrasts, one per task
for c = 2:numel(P.Tasks)
    P.Contrasts(c-1) = struct( ...
        'left', {P.Tasks(c)}, ...
        'right', {{'none'}}, ...
        'STAT', 'T' ...
        );
end

addpath([pwd '/external/spm8_r6313/spm8'])
addpath(genpath([pwd '/external/gppi']))
save([pwd '/../OUTPUTS/BSNT_L_PPI.mat'],'P')
PPPI([pwd '/../OUTPUTS/BSNT_L_PPI.mat'])

